meta_name: "My Only Sub"
meta_title: "My Only Sub - One sub to watch them all"
meta_description: "Optimize your streaming subscriptions in just a few clicks"
meta_image: "MOS-cover-min.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards
  